#pragma once

enum class DOTA_GAME_STATE : int {
    INVALID = -1,
    INIT,
    WAIT_FOR_PLAYERS_TO_LOAD,
    HERO_SELECTION,
    STRATEGY_TIME,
    PRE_GAME,
    GAME_IN_PROGRESS,
    POST_GAME,
    DISCONNECT,
    TEAM_SHOWCASE,
    CUSTOM_GAME_SETUP,
    WAIT_FOR_MAP_TO_LOAD,
    SCENARIO_SETUP,
    PLAYER_DRAFT,
    LAST
};

enum class ENTITY_NAME_TYPE {
    INTERNAL_NAME,
    ENTITY_NAME,
    BINARY_NAME,
    CLASS_NAME
};

enum class PATCH_TYPE {
    JE = 0x74,
    JNE = 0x75,
    TEST = 0x85,
    JMP = 0xEB,
    CUSTOM = 0x0
};

enum class ASM_TYPE {
    LEA, // 3, 7
    CALL // 2, 6
};

enum class DOTA_WEATHER {
    WEATHER_DEFAULT,
    WEATHER_SNOW,
    WEATHER_RAIN,
    WEATHER_MOONBEAM,
    WEATHER_PESTILENCE,
    WEATHER_HARVEST,
    WEATHER_SIROCCO,
    WEATHER_SPRING,
    WEATHER_ASH,
    WEATHER_AURORA
};

enum class DOTA_RIVER {
    RIVER_DEFAULT,
    RIVER_OIL,
    RIVER_DRY,
    RIVER_SLIME,
    RIVER_CHROME,
    RIVER_ELECTRIC,
    RIVER_POTION,
    RIVER_BLOOD
};
