name: Build C++ (MSBuild) and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Release x64
        run: msbuild Dota2Patcher.sln /p:Configuration=Release /p:Platform=x64

      - name: Locate built EXE
        id: find_exe
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Filter Dota2Patcher.exe -Recurse | Select-Object -First 1
          if (-not $exe) { Write-Error "EXE not found"; exit 1 }
          echo "EXE_PATH=$($exe.FullName)" >> $env:GITHUB_ENV
          echo "Found EXE at: $($exe.FullName)"

      - name: Create GitHub Release and Upload EXE
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.EXE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
