name: Build C++ (MSBuild) and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Release x64
        run: msbuild Dota2Patcher.sln /p:Configuration=Release /p:Platform=x64

      - name: Create GitHub Release and Upload EXE
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/x64/Release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug — List build output
        run: dir D:\a\Dota2Patcher\Dota2Patcher /s /b
